import { Component } from '@angular/core';
import { AlertComponent } from '@shared/components/alert/alert.component';

@Component({
  selector: 'app-level-up-cheat-sheet',
  standalone: true,
  imports: [AlertComponent],
  templateUrl: './level-up-cheat-sheet.component.html',
  styleUrl: './level-up-cheat-sheet.component.css',
})
export class LevelUpCheatSheetComponent {
  readonly data = [
    {
      level: 1,
      duration: 1,
      totalDuration: 1,
      cost: 1,
      totalCost: 1,
    },
    {
      level: 2,
      duration: 2,
      totalDuration: 3,
      cost: 2,
      totalCost: 3,
    },
    {
      level: 3,
      duration: 3,
      totalDuration: 6,
      cost: 3,
      totalCost: 6,
    },
    {
      level: 4,
      duration: 4,
      totalDuration: 10,
      cost: 4,
      totalCost: 10,
    },
    {
      level: 5,
      duration: 5,
      totalDuration: 15,
      cost: 10,
      totalCost: 20,
    },
    {
      level: 6,
      duration: 6,
      totalDuration: 21,
      cost: 6,
      totalCost: 26,
    },
    {
      level: 7,
      duration: 7,
      totalDuration: 28,
      cost: 7,
      totalCost: 33,
    },
    {
      level: 8,
      duration: 8,
      totalDuration: 36,
      cost: 8,
      totalCost: 41,
    },
    {
      level: 9,
      duration: 9,
      totalDuration: 45,
      cost: 9,
      totalCost: 50,
    },
    {
      level: 10,
      duration: 10,
      totalDuration: 55,
      cost: 30,
      totalCost: 80,
    },
    {
      level: 11,
      duration: 11,
      totalDuration: 66,
      cost: 11,
      totalCost: 91,
    },
    {
      level: 12,
      duration: 12,
      totalDuration: 78,
      cost: 12,
      totalCost: 103,
    },
    {
      level: 13,
      duration: 13,
      totalDuration: 91,
      cost: 13,
      totalCost: 116,
    },
    {
      level: 14,
      duration: 14,
      totalDuration: 105,
      cost: 14,
      totalCost: 130,
    },
    {
      level: 15,
      duration: 15,
      totalDuration: 120,
      cost: 15,
      totalCost: 145,
    },
    {
      level: 16,
      duration: 16,
      totalDuration: 136,
      cost: 16,
      totalCost: 161,
    },
    {
      level: 17,
      duration: 17,
      totalDuration: 153,
      cost: 17,
      totalCost: 178,
    },
    {
      level: 18,
      duration: 18,
      totalDuration: 171,
      cost: 18,
      totalCost: 196,
    },
    {
      level: 19,
      duration: 19,
      totalDuration: 190,
      cost: 19,
      totalCost: 215,
    },
    {
      level: 20,
      duration: 20,
      totalDuration: 210,
      cost: 60,
      totalCost: 275,
    },
  ];
}
